DROP TABLE IF EXISTS ORDERS;
DROP SEQUENCE IF EXISTS ORDERS_SEQ;

CREATE SEQUENCE ORDERS_SEQ;
CREATE TABLE ORDERS (
    ID BIGINT DEFAULT ORDERS_SEQ.NEXTVAL PRIMARY KEY,
    ITEM VARCHAR(1000) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0
);
